<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_yewuxitong</name>
   <tag></tag>
   <elementGuidId>ae3bba64-8674-4fb8-822d-b58f16b0ae40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;app&quot;]/div/div[2]/div[1]/div[1]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#app > div > div.m_col > div.ilay1 > div:nth-child(1) > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1596783967720</value>
   </webElementProperties>
</WebElementEntity>
