<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i__zhankai</name>
   <tag></tag>
   <elementGuidId>cb5fb5bd-51d2-4951-b134-8a4358a7ec0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div/div/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.trigger.ivu-icon.ivu-icon-ios-arrow-back</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>trigger ivu-icon ivu-icon-ios-arrow-back</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;ivu-layout ivu-layout-has-sider layout tablet&quot;]/div[@class=&quot;ivu-layout sidemenu content-width-Fixed&quot;]/div[@class=&quot;header-animat&quot;]/div[@class=&quot;ivu-layout-header header-fixedHeader header-side-opened&quot;]/div[@class=&quot;header&quot;]/i[@class=&quot;trigger ivu-icon ivu-icon-ios-arrow-back&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div/div/div/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/i</value>
   </webElementXpaths>
</WebElementEntity>
